name: Pre-release Build Validation Scripts

on: 
  push:
    branches:
      - master
    paths:
      - 'build-validation-scripts/**'
  workflow_dispatch:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: jhurne/experiment-automation
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      -  name: Build with Gradle
         uses: gradle/gradle-build-action@v2
         with:
           arguments: build
           build-root-directory: build-validation-scripts/distribution-build
      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "build-validation-development-latest"
          prerelease: true
          title: "Build Validation - Development Build"
          files: "build-validation-scripts/distribution-build/build/distributions/*.zip"

